ppw/urls.py
from django.urls import include,path
from django.contrib import admin
from . import views

urlpatterns = [
    path('',views.index, name='index'),
    path('signup',views.signup, name='signup'),
    path('background',views.background, name='background'),
    path('showSchedule',views.showSchedule, name='showSchedule'),
    path('addSchedule',views.addSchedule, name='addSchedule'),
    path('delSchedule',views.delSchedule, name='delSchedule')
]

ppw_project/urls.py
from django.contrib import admin
from django.urls import include, path
from ppw.views import index
from story9 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ppw/',include('ppw.urls')),
    path('story6/',include('story6.urls')),
    path('story9/',include('story9.urls')),
    path('auth/', include('social_django.urls', namespace='social')),  # Google oauth
    path('', views.index),
]

story9/urls.py
from django.urls import include,path
from django.contrib import admin
from . import views

app_name = 'story9'
urlpatterns = [
    path('',views.index,name='index'),
    path('register',views.register,name='register'),
    path('api/getEmail',views.get_email,name="get_email"),
    path('api/register',views.api_register,name='api_register'),
    path('logout/',views.logout_page,name='logout'),
]

story9/models.py
from django.db import models

# Create your models here.
class Subscriber(models.Model):
    name = models.CharField(max_length=30)
    email = models.CharField(max_length=30)
    password = models.CharField(max_length=30)

    # def __str__(self):
    #     return self.name

story9/forms.py
from django import forms

class add_subscriber(forms.Form):
    name_attrs = {
        'id' : 'user_name',
        'type' : 'text',
        'class' : 'form-control form-override',
        'placeholder' : 'Name'
    }
    password_attrs = {
        'id' : 'user_password',
        'type' : 'password',
        'class' : 'form-control form-override',
        'placeholder' : 'Password'
    }
    email_attrs = {
        'id' : 'user_email',
        'type' : 'email',
        'class' : 'form-control form-override',
        'placeholder' : 'Email'
    }

    name = forms.CharField(label='', required=True, max_length=30, widget=forms.TextInput(attrs=name_attrs))
    password = forms.CharField(label='', required=True, max_length=30, widget=forms.TextInput(attrs=password_attrs))
    email = forms.CharField(label='', required=True, max_length=30, widget=forms.TextInput(attrs=email_attrs))

story9/views.py
from django.shortcuts import render,reverse

# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect
from .forms import add_subscriber
from .models import Subscriber

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth import authenticate,logout

def index(request):
    return render(request, 'story9/index.html')

def register(request):
    # all_subscriber = Subscriber.objects.all()

    if request.method == 'POST':
        form = add_subscriber(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            subscriber = Subscriber(
                name = cleaned_data['name'],
                password = cleaned_data['password'],
                email = cleaned_data['email'])
            subscriber.save()
            return HttpResponseRedirect('register')
        
        return HttpResponse('error')
    else:
        form = add_subscriber()
    
    response = {
        'form' : form
    }
    return render(request, 'story9/register.html',response)

def get_email(request):
    subs = Subscriber.objects.all()
    data = {"data":list(subs.values("email"))}
    return JsonResponse(data)

def api_register(request): 
    if (request.method == 'POST'): 
        form = add_subscriber(request.POST) 
        if (form.is_valid()): 
            name = form.cleaned_data['name'] 
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']  
            new_sub = Subscriber(name=name, password=password, email=email) 
            new_sub.save() 
            return JsonResponse({'success': True}) 
    return JsonResponse({'success': False})

def logout_page(request):
    request.session.flush()
    return HttpResponseRedirect(reverse('story9:index'))
    # response = HttpResponseRedirect('./index')
    # logout(request)
    # return response

templates/story9/index.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <title>Book Collection</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/solid.css" integrity="sha384-rdyFrfAIC05c5ph7BKz3l5NG5yEottvO/DQ0dCrwD8gzeQDjYBHNr1ucUpQuljos"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/fontawesome.css" integrity="sha384-u5J7JghGz0qUrmEsWzBQkfvc8nK3fUT7DCaQzNQ+q4oEXhGSx+P2OqjWsfIRB8QT"
        crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'story9/styles.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body class="index-body">
    <div class="content-wrapper">
        <div class="head-wrapper">

            {% if user.is_authenticated %}
            <div class="">
                <p class="display-4">Hello, {{ user.username }}</p>
                <a id="logout-button" href="{% url 'story9:logout' %}" class="btn btn-outline-light btn-override">Logout</a>
            </div>
            {% else %}
            <br>
            <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-outline-light btn-override">Login with Google</a><br>
            {% endif %}

            <h1>Michael's Book Collection</h1>

            <div class="favorites-wrapper">
                <div class="favorites-text">
                    <h1>Favorite Books: </h1>
                </div>
                <div class="favorites-counter">
                    <h1></h1>
                </div>
                <div>
                </div>
            </div>
            <div class="filter-wrapper">
                <input id="filter-textarea" type="text" class="form-control form-override" placeholder="Search for keyword"
                    aria-label="Recipient's username" aria-describedby="basic-addon2">
                <br>
                <button id="filter-button" type="button" class="btn btn-outline-light btn-override">Search</button>
                <br>
            </div>
            <div class="table-wrapper">
                <table class="table table-striped table-bordered table-override">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Image</th>
                            <th>Title</th>
                            <th>Author</th>
                            <th>Favorites</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>

        <script src="{% static 'story9/script.js' %}"></script>
</body>

</html>

templates/story9/register.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <title>Register Validation</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/solid.css" integrity="sha384-rdyFrfAIC05c5ph7BKz3l5NG5yEottvO/DQ0dCrwD8gzeQDjYBHNr1ucUpQuljos"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/fontawesome.css" integrity="sha384-u5J7JghGz0qUrmEsWzBQkfvc8nK3fUT7DCaQzNQ+q4oEXhGSx+P2OqjWsfIRB8QT"
        crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'story9/styles.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body class="register-body">

    <section id="form">
        <div class="container form-content-override">
            <form id="subscriber-form" action="{% url 'story9:register' %}" method="post">
                {% csrf_token %}
                <div class="form-header">
                    Register
                </div>
                {% csrf_token %}
                <div class="row my-2 form-content-override">Name{{ form.name }}</div>
                <div class="row my-2 form-content-override">Password{{ form.password }}</div>
                <div class="row my-2 form-content-override">Email{{ form.email }}</div>

                <div class="button-submit horizontal-flex">
                    <button id="button-form-validate" class="btn btn-outline-light btn-form-override" type="submit" name="action">
                        Register
                    </button>
                </div>
                <div class="horizontal-flex"><p id="notif-error"></p></div>
            </form>
        </div>
    </section>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>

<script src="{% static 'story9/script.js' %}"></script>

</html>